In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.random_normal_initializer()
y = x(shape=[5,5], dtype=None, partition_info=None)

In [3]:
def random_normal_initializer(mean = 0.0, stddev = 1.0):
    def random_normal(shape, dtype = tf.float32, partition_info = None):
        return tf.random_normal(shape=shape, mean=mean, stddev=stddev)
    return random_normal
def identity_initializer(tensor):
    def identity(shape, dtype = tf.float32, partition_info = None):
        return tf.identity(tensor)
    return identity

In [4]:
range_ = tf.cast(tf.range(5), dtype = tf.float32)

In [6]:
with tf.variable_scope("ex") as scope:
    w = tf.get_variable("weight", shape=[2, 2], dtype=tf.float32, initializer=random_normal_initializer())
    b = tf.get_variable("bias", shape=[2], dtype=tf.float32, initializer=identity_initializer(range_) )

In [8]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(w))
print(sess.run(b))

[[-1.19857717  1.12051129]
 [-0.52025568 -0.5067327 ]]
[ 0.  1.  2.  3.  4.]


In [9]:
print(sess.run(range_))

[ 0.  1.  2.  3.  4.]
